export const API_KEY = 'AIzaSyBPHfRKQTL3YLH9kcftWsr5p0dQgJzPYnE'
export const AUTH_DOMAIN = 'expo-deneme-ea29b.firebaseapp.com'
export const DATABASE_URL = 'https://expo-deneme-ea29b.firebaseio.com'
export const PROJECT_ID = 'expo-deneme-ea29b'
export const STORAGE_BUCKET = 'expo-deneme-ea29b.appspot.com'
export const MESSAGIN_SENDER_ID = '367978798857'
